### ISSUE TITLE
Add Stops property to Linear Gradient

### ISSUE THREAD

**Issue by kauelima** [victoreronmosele/flutter_gradient_generator#54]
First, thanks for the tool! As a designer, it helped me a lot to understand how gradients are built in flutter.

I would like to see other Linear Gradient class properties added to the tool in the future.

With the code generated by your tool, I was able to imply how to build my gradient using the stops I wanted, but it would be spectacular for other people to use in the future for this feature to be added.

Doc reference: https://api.flutter.dev/flutter/painting/LinearGradient-class.html

**Comment by victoreronmosele** [comment]
Hi @kauelima, thanks for this suggestion.  I'm glad to know the tool was helpful!

I agree with your comment, the stops property will definitely make the tool more helpful to people and I will definitely be working on this.

Concerning the stop feature, is there any specific way you envision it to work? Please let me know.

**Comment by kauelima** [comment]
I like the way this tool works: https://cssgradient.io/ works. Maybe the interface is a little bit cluttered, but specially the section on the right with a list of all colors and their Hex and stops seem to be a good way. 

![Screenshot 2023-01-12 at 09 40 50](https://user-images.githubusercontent.com/1977274/212069056-c36b3541-98a6-41b2-9378-23769998706a.png)

I think this is a good way because most people already have hex codes, but having your popover to choose another color is a better way than presenting it right on the page.

**Comment by victoreronmosele** [comment]
@kauelima please check out the stops feature I added in this preview link for the stops PR.

- [Preview link ](https://flutter-gradient-generator--pr59-feat-add-stops-to-gr-jeemqoq7.web.app/.
)
- [PR link](https://github.com/victoreronmosele/flutter_gradient_generator/pull/59)

Please let me know what you think.

**Comment by kauelima** [comment]
Awesome @victoreronmosele ! It works great :) thank you!

**Comment by victoreronmosele** [comment]
Great @kauelima! 

I'll add some finishing touches to it and merge that in so it's live.

And please feel free to add more feature requests! :)
