### ISSUE TITLE
[Bug] Can not input hex color when add color

### ISSUE THREAD

**Issue by duchm-cyberk** [victoreronmosele/flutter_gradient_generator#72]
**Issue:**
When attempt to change hex color code of added colors, with delete or type in any characters, does not mutate hex color value. In case of deletion, causing added colors to be removed.

https://github.com/victoreronmosele/flutter_gradient_generator/assets/137751295/090b320f-f1a2-41d6-8107-1c191b543a46

**Expected:**
Can change hex color for each added color individually

**Actual:**
Hex value not changing, colors not apply

**Comment by victoreronmosele** [comment]
Thank you, @duchmse23, for raising this issue. 

I am currently working on replacing the color picker with an HTML color input, which should resolve the problem. 

Changes are being made in #71.

**Comment by victoreronmosele** [comment]
Please use https://flutter-gradient-generator--pr71-feature-html-color-p-lwhh3u3n.web.app/ for the time being while I work on merging the changes in #71.

**Comment by victoreronmosele** [comment]
@duchmse23, the issue has been resolved. 

Please test it on the main website https://fluttergradientgenerator.com. Let me know if it solves the issue. 

Here's a screen recording for your reference:


https://github.com/victoreronmosele/flutter_gradient_generator/assets/19398044/c4f00512-2c0c-47fe-9895-e68802c077f4

**Comment by victoreronmosele** [comment]
@duchmse23 I am closing this issue as resolved since the bug has been fixed. 

Please feel free to reopen it if you're still facing the bug.
